services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_DB=photoselect
      - POSTGRES_PASSWORD=photoselect
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=photoselect
      - MINIO_ROOT_PASSWORD=photoselect
    command:
      - server
      - /minio/data
      - --console-address
      - :9001
volumes:
  db-data:
  rabbitmq_data:
  minio_data:
networks:
  spring-postgres:
